/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classe.Cliente;
import Dados.DadosCliente;
import Negocio.NegocioCliente;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class ClienteGUIEditar extends javax.swing.JFrame {

    ArrayList<Cliente> respostaCpf = new ArrayList<>();

    public void ResetarTabela() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Nome", "Cpf", "Rg"});
        jTableCliente.setModel(modelo);
    }

    public void ListarCpf() {

        try {
            Cliente cliente = new Cliente();
            DadosCliente dados = new DadosCliente();
            this.respostaCpf = dados.listarClientes(cliente);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (Cliente c : this.respostaCpf) {
                modelo.addElement(c.getCpf());
            }

            jComboBoxCpfCliente.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    public ClienteGUIEditar() {
        initComponents();
        ListarCpf();
        ResetarTabela();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelSelecionarCliente = new javax.swing.JLabel();
        jComboBoxCpfCliente = new javax.swing.JComboBox<>();
        jLabelNovoNomeCliente = new javax.swing.JLabel();
        jLabelNovoCpfCliente = new javax.swing.JLabel();
        jLabelNovoRgCliente = new javax.swing.JLabel();
        jTextFieldNovoNomeCliente = new javax.swing.JTextField();
        jTextFieldNovoCpfCliente = new javax.swing.JTextField();
        jTextFieldNovoRgCliente = new javax.swing.JTextField();
        jButtonEditarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jButtonConsultar = new javax.swing.JButton();
        jLabelInformacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Editar Cliente");

        jLabelSelecionarCliente.setText("Selecione o Cliente para edição:");

        jComboBoxCpfCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCpfCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxCpfClienteMouseClicked(evt);
            }
        });

        jLabelNovoNomeCliente.setText("Novo Nome:");

        jLabelNovoCpfCliente.setText("Novo Cpf:");

        jLabelNovoRgCliente.setText("Novo Rg:");

        jTextFieldNovoCpfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNovoCpfClienteKeyTyped(evt);
            }
        });

        jTextFieldNovoRgCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNovoRgClienteKeyTyped(evt);
            }
        });

        jButtonEditarCliente.setText("Editar");
        jButtonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarClienteActionPerformed(evt);
            }
        });

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableClienteMousePressed(evt);
            }
        });
        jTableCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableClienteKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabelInformacao.setText("Não é permitido a edição de cliente com vinculo a Ordem de serviço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSelecionarCliente)
                        .addGap(81, 81, 81)
                        .addComponent(jComboBoxCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNovoNomeCliente)
                                .addComponent(jLabelNovoRgCliente)
                                .addComponent(jLabelNovoCpfCliente))
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldNovoCpfCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNovoNomeCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                .addComponent(jTextFieldNovoRgCliente)))))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButtonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabelInformacao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabelInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar)
                    .addComponent(jLabelSelecionarCliente))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNovoNomeCliente)
                        .addGap(32, 32, 32)
                        .addComponent(jLabelNovoCpfCliente)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelNovoRgCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNovoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldNovoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldNovoRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jButtonEditarCliente)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCpfClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCpfClienteMouseClicked


    }//GEN-LAST:event_jComboBoxCpfClienteMouseClicked

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:

        try {

            if (jComboBoxCpfCliente.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem cliente para Editar");
                dispose();
                return;
                
            }
            Cliente cliente = new Cliente();

            cliente.setCpf(jComboBoxCpfCliente.getSelectedItem().toString());

            DadosCliente dados = new DadosCliente();
            this.respostaCpf = dados.listarClientes(cliente);

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Nome", "Cpf", "Rg"});

            for (Cliente c : this.respostaCpf) {
                modelo.addRow(new Object[]{c.getNome(), c.getCpf(), c.getRg()});
            }

            jTableCliente.setModel(modelo);

        } catch (Exception ex) {
            Logger.getLogger(ClienteGUIEditar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarClienteActionPerformed
        // TODO add your handling code here:

        try {
            
            if (jComboBoxCpfCliente.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem cliente para Editar");
                dispose();
                return;
                
            }

            Cliente clienteNovo = new Cliente();
            Cliente clienteVelho = new Cliente();

            clienteNovo.setNome(jTextFieldNovoNomeCliente.getText());
            clienteNovo.setCpf(jTextFieldNovoCpfCliente.getText());
            clienteNovo.setRg(jTextFieldNovoRgCliente.getText());
            clienteVelho.setCpf(jComboBoxCpfCliente.getSelectedItem().toString());

            NegocioCliente negocio = new NegocioCliente();

            negocio.editarCliente(clienteNovo, clienteVelho);

            int resposta = JOptionPane.showConfirmDialog(rootPane, "Cliente Alterado! \n Deseja Editar outro cliente ?", "Sucesso", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if (resposta == JOptionPane.YES_OPTION) {
                ListarCpf();
                ResetarTabela();

                jTextFieldNovoCpfCliente.setText("");
                jTextFieldNovoNomeCliente.setText("");
                jTextFieldNovoRgCliente.setText("");
                jTextFieldNovoNomeCliente.requestFocus();
            } else {
                dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }


    }//GEN-LAST:event_jButtonEditarClienteActionPerformed

    private void jTextFieldNovoCpfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNovoCpfClienteKeyTyped
        // TODO add your handling code here:
        
        char digito = evt.getKeyChar();

        if (!(digito >= 48 && digito <= 57)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNovoCpfClienteKeyTyped

    private void jTextFieldNovoRgClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNovoRgClienteKeyTyped
        // TODO add your handling code here:
        char digito = evt.getKeyChar();

        if (!(digito >= 48 && digito <= 57)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNovoRgClienteKeyTyped

    private void jTableClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMousePressed
        // TODO add your handling code here:
        jTableCliente.editingCanceled(null);
        jTableCliente.editingStopped(null);
    }//GEN-LAST:event_jTableClienteMousePressed

    private void jTableClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableClienteKeyTyped
        // TODO add your handling code here:
        jTableCliente.editingCanceled(null);
        jTableCliente.editingStopped(null);
    }//GEN-LAST:event_jTableClienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUIEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUIEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUIEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUIEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteGUIEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonEditarCliente;
    private javax.swing.JComboBox<String> jComboBoxCpfCliente;
    private javax.swing.JLabel jLabelInformacao;
    private javax.swing.JLabel jLabelNovoCpfCliente;
    private javax.swing.JLabel jLabelNovoNomeCliente;
    private javax.swing.JLabel jLabelNovoRgCliente;
    private javax.swing.JLabel jLabelSelecionarCliente;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldNovoCpfCliente;
    private javax.swing.JTextField jTextFieldNovoNomeCliente;
    private javax.swing.JTextField jTextFieldNovoRgCliente;
    // End of variables declaration//GEN-END:variables
}
