/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classe.Cliente;
import Dados.DadosCliente;
import Negocio.NegocioCliente;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class ClienteGUIRemover extends javax.swing.JFrame {

    ArrayList<Cliente> respostaCpf = new ArrayList<>();
    ArrayList<Cliente> resposta = new ArrayList<>();

    public void ResetarTabela() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Nome", "Cpf", "Rg"});
        jTableRemover.setModel(modelo);
    }

    public void ListarCpf() {

        try {
            Cliente cliente = new Cliente();
            DadosCliente dados = new DadosCliente();
            this.respostaCpf = dados.listarClientes(cliente);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (Cliente c : this.respostaCpf) {
                modelo.addElement(c.getCpf());
            }

            jComboBoxCpfCliente.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    public ClienteGUIRemover() {
        initComponents();
        ListarCpf();
        ResetarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelSelecionarCLiente = new javax.swing.JLabel();
        jComboBoxCpfCliente = new javax.swing.JComboBox<>();
        jButtonRemoverCliente = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRemover = new javax.swing.JTable();
        jLabelInformacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Remover Cliente");

        jLabelSelecionarCLiente.setText("Selecione o Cliente que deseja Remover:");

        jComboBoxCpfCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonRemoverCliente.setText("Remover");
        jButtonRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverClienteActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jTableRemover.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableRemoverMousePressed(evt);
            }
        });
        jTableRemover.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableRemoverKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRemover);

        jLabelInformacao.setText("Não é permitido remover o cliente com vinculo a Ordem de serviço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButtonRemoverCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelSelecionarCLiente)
                                .addGap(39, 39, 39)
                                .addComponent(jComboBoxCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelInformacao)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelecionarCLiente)
                    .addComponent(jButtonConsultar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRemoverCliente)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverClienteActionPerformed
        // TODO add your handling code here:

        try {
            
            if (jComboBoxCpfCliente.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem cliente para remover");
                dispose();
                return;
            }

            Cliente cliente = new Cliente();
            cliente.setCpf(jComboBoxCpfCliente.getSelectedItem().toString());
            NegocioCliente negocio = new NegocioCliente();
            negocio.removerCliente(cliente);

            int resposta = 0;

            resposta = JOptionPane.showConfirmDialog(rootPane, "Cliente removido! \n Deseja Remover outro cliente ?", "Sucesso", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);   

            if (resposta == JOptionPane.YES_OPTION) {
                ResetarTabela();
                ListarCpf();
            } else {
                dispose();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_jButtonRemoverClienteActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:

        try {

            if (jComboBoxCpfCliente.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem cliente para remover");
                dispose();
                return;
            }

            Cliente cliente = new Cliente();
            cliente.setCpf(jComboBoxCpfCliente.getSelectedItem().toString());

            DadosCliente dadosClientes = new DadosCliente();

            this.resposta = dadosClientes.listarClientes(cliente);

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Nome", "Cpf", "Rg"});
            for (Cliente c : this.resposta) {
                modelo.addRow(new Object[]{c.getNome(), c.getCpf(), c.getRg()});
            }

            jTableRemover.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jTableRemoverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableRemoverKeyTyped
        // TODO add your handling code here:
        jTableRemover.editingCanceled(null);
        jTableRemover.editingStopped(null);
        
    }//GEN-LAST:event_jTableRemoverKeyTyped

    private void jTableRemoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRemoverMousePressed
        // TODO add your handling code here:
        jTableRemover.editingCanceled(null);
        jTableRemover.editingStopped(null);
    }//GEN-LAST:event_jTableRemoverMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteGUIRemover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonRemoverCliente;
    private javax.swing.JComboBox<String> jComboBoxCpfCliente;
    private javax.swing.JLabel jLabelInformacao;
    private javax.swing.JLabel jLabelSelecionarCLiente;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRemover;
    // End of variables declaration//GEN-END:variables
}
