/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classe.Cliente;
import Classe.OrdemDeServico;
import Dados.DadosCliente;
import Dados.DadosOrdemDeServico;
import Negocio.NegocioOrdemDeServico;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class OrdemGUIRemover extends javax.swing.JFrame {

    ArrayList<OrdemDeServico> ListarOs = new ArrayList<>();

    public void ResetarTabela() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Numero", "Cpf Cliente", "Matricula Funcionario", "Problema", "Data_Cadastro"});
        jTableOrdemDeServico.setModel(modelo);
    }

    public void ListarNumeroOrdemDeServico() {
        try {
            OrdemDeServico os = new OrdemDeServico();
            DadosOrdemDeServico dados = new DadosOrdemDeServico();
            this.ListarOs = dados.listarOrdemServicos(os);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (OrdemDeServico o : this.ListarOs) {

                if ("Aberta".equals(o.Status())) {
                    modelo.addElement(o.getNumero());
                }
            }

            jComboBoxConsultarOS.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    public OrdemGUIRemover() {
        initComponents();
        ResetarTabela();
        ListarNumeroOrdemDeServico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jButtonConsultar = new javax.swing.JButton();
        jLabelInformacao = new javax.swing.JLabel();
        jComboBoxConsultarOS = new javax.swing.JComboBox();
        jButtonRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrdemDeServico = new javax.swing.JTable();
        jLabelTitulo = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabelInformacao.setText("Selecione a Ordem de serviço desejada :");

        jComboBoxConsultarOS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jTableOrdemDeServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableOrdemDeServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableOrdemDeServicoMousePressed(evt);
            }
        });
        jTableOrdemDeServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableOrdemDeServicoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOrdemDeServico);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setText("Remover ordem de serviço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelInformacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxConsultarOS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitulo)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConsultarOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar)
                    .addComponent(jLabelInformacao))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonRemover)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed

        try {

            if (jComboBoxConsultarOS.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem Ordem de Serviço para consulta");
                dispose();
                return;
            }

            OrdemDeServico os = new OrdemDeServico();
            os.setNumero(Integer.parseInt(jComboBoxConsultarOS.getSelectedItem().toString()));

            DadosOrdemDeServico DadosOS = new DadosOrdemDeServico();

            this.ListarOs = DadosOS.listarOrdemServicos(os);

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Numero", "Cliente_Cpf", "Matricula_funcionario", "Problema", "Data_Cadastro"});
            for (OrdemDeServico o : ListarOs) {

                if ("Aberta".equals(o.Status())) {
                    modelo.addRow(new Object[]{o.getNumero(), o.getCliente().getCpf(), o.getFuncionario().getMatricula(), o.getClassificacaoProblema().getNome(), o.getDataCadastro()});

                }
            }

            jTableOrdemDeServico.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        try {

            if (jComboBoxConsultarOS.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem Ordem de serviço para remover");
                dispose();
                return;
            }
            OrdemDeServico OS = new OrdemDeServico();
            OS.setNumero(Integer.parseInt(jComboBoxConsultarOS.getSelectedItem().toString()));

            NegocioOrdemDeServico Negocio = new NegocioOrdemDeServico();
            Negocio.removerOrdemServico(OS);

            int resposta = JOptionPane.showConfirmDialog(rootPane, "Ordem de serviço removida! \nDeseja Remover outra ordem de serviço ? ", "Sucesso", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if (resposta == JOptionPane.YES_OPTION) {
                ResetarTabela();
                ListarNumeroOrdemDeServico();
            } else {
                dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jTableOrdemDeServicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableOrdemDeServicoKeyTyped
        // TODO add your handling code here:
        jTableOrdemDeServico.editingCanceled(null);
        jTableOrdemDeServico.editingStopped(null);
    }//GEN-LAST:event_jTableOrdemDeServicoKeyTyped

    private void jTableOrdemDeServicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrdemDeServicoMousePressed
        // TODO add your handling code here:
        jTableOrdemDeServico.editingCanceled(null);
        jTableOrdemDeServico.editingStopped(null);
    }//GEN-LAST:event_jTableOrdemDeServicoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemGUIRemover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBoxConsultarOS;
    private javax.swing.JLabel jLabelInformacao;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOrdemDeServico;
    // End of variables declaration//GEN-END:variables
}
