/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classe.ClassificacaoProblema;
import Classe.Cliente;
import Classe.Funcionario;
import Classe.OrdemDeServico;
import Dados.DadosClassificacaoProblema;
import Dados.DadosCliente;
import Dados.DadosFuncionario;
import Negocio.NegocioOrdemDeServico;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class OrdemGUICadastrar extends javax.swing.JFrame {

    ArrayList<Cliente> respostaCpf = new ArrayList<>();
    ArrayList<Funcionario> respostaMatricula = new ArrayList<>();
    ArrayList<ClassificacaoProblema> respostaCodigo = new ArrayList<>();
    
    public void listarCpf(){
    
        try {
            
            Cliente cliente = new Cliente();
            
            DadosCliente dados = new DadosCliente();
            
            this.respostaCpf = dados.listarClientes(cliente);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (Cliente c : this.respostaCpf) {
                modelo.addElement(c.getNome() + "   |   " + c.getCpf());
            }

            jComboBoxCliente.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    
    public void listarMatricula(){
    
        try {
            
            Funcionario funcionario = new Funcionario();
            
            DadosFuncionario dados = new DadosFuncionario();
            
            this.respostaMatricula = dados.listarFuncionarios(funcionario);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            
            for (Funcionario f : respostaMatricula) {
                modelo.addElement(f.getNome() + "   |   " + f.getMatricula());
            }
            
            jComboBoxFuncionario.setModel(modelo);

        }catch (Exception e){
        
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            
        }
        
    }
    
    public void  listarCodigo(){
    
        try{
            
            ClassificacaoProblema classificacao = new ClassificacaoProblema();
            DadosClassificacaoProblema dados = new DadosClassificacaoProblema();
            
            this.respostaCodigo = dados.listarClassificacaoProblemas(classificacao);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            
            for (ClassificacaoProblema p : respostaCodigo) {
                modelo.addElement(p.getNome() + "   |   " + p.getCodigo());
            }
            
            jComboBoxProblema.setModel(modelo);
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        
    }
    public OrdemGUICadastrar() {
        initComponents();
        listarCodigo();
        listarCpf();
        listarMatricula();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldDataCadastro.setText(formato.format(new Date(System.currentTimeMillis())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelDescricaoProblema = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelDataCadastro = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox();
        jLabelFuncionario = new javax.swing.JLabel();
        jComboBoxFuncionario = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxProblema = new javax.swing.JComboBox();
        jButtonCadastrarOS = new javax.swing.JButton();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");

            jTextFieldDataCadastro = new javax.swing.JFormattedTextField(data);
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setText("Cadastrar Ordem De Servico");

        jLabelDescricaoProblema.setText("Descrição Problema da Ordem de Serviço:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelDataCadastro.setText("Data de Cadastro:");

        jLabelCliente.setText("Cliente:");

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelFuncionario.setText(" Funcionario:");

        jComboBoxFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText(" Problema:");

        jComboBoxProblema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCadastrarOS.setText("Cadastrar");
        jButtonCadastrarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelTitulo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelDescricaoProblema)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDataCadastro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelCliente)
                                            .addComponent(jLabelFuncionario)
                                            .addComponent(jLabel1))
                                        .addGap(28, 28, 28)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxProblema, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButtonCadastrarOS)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelTitulo)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelDescricaoProblema)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataCadastro)
                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncionario)
                    .addComponent(jComboBoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addComponent(jButtonCadastrarOS)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarOSActionPerformed
        // TODO add your handling code here:
        
        try{
            
            OrdemDeServico os = new OrdemDeServico();
            
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataCadastro = new java.sql.Date (formato.parse(jTextFieldDataCadastro.getText()).getTime());
            os.setDescricaoProblema(jTextArea1.getText());
            os.setDataCadastro (dataCadastro);
            
            int indexComboCliente = jComboBoxCliente.getSelectedIndex();
            int indexComboFuncionario = jComboBoxFuncionario.getSelectedIndex();
            int indexComboProblema = jComboBoxProblema.getSelectedIndex();
            
            Cliente cliente = this.respostaCpf.get(indexComboCliente);
            Funcionario funcionario = this.respostaMatricula.get(indexComboFuncionario);
            ClassificacaoProblema problema = this.respostaCodigo.get(indexComboProblema);
            
            os.setCliente(cliente);
            os.setClassificacaoProblema(problema);
            os.setFuncionario(funcionario);

            NegocioOrdemDeServico negocio = new NegocioOrdemDeServico();
            negocio.cadastrarOrdemServico(os);
            
            JOptionPane.showMessageDialog(rootPane,"Ordem de Serviço Cadastrada");
  
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
    }//GEN-LAST:event_jButtonCadastrarOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemGUICadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemGUICadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemGUICadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemGUICadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemGUICadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarOS;
    private javax.swing.JComboBox jComboBoxCliente;
    private javax.swing.JComboBox jComboBoxFuncionario;
    private javax.swing.JComboBox jComboBoxProblema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelDataCadastro;
    private javax.swing.JLabel jLabelDescricaoProblema;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDataCadastro;
    // End of variables declaration//GEN-END:variables
}
