/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classe.OrdemDeServico;
import Dados.DadosOrdemDeServico;
import Negocio.NegocioOrdemDeServico;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class OrdemGUIStatus extends javax.swing.JFrame {

    ArrayList<OrdemDeServico> ListarOs = new ArrayList<>();

    public void ResetarTabela() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Numero", "Cpf Cliente", "Matricula Funcionario", "Problema", "Data_Cadastro"});
        jTableConsulta.setModel(modelo);
    }

    public void ListarNumeroOrdemDeServico() {
        try {
            OrdemDeServico os = new OrdemDeServico();
            DadosOrdemDeServico dados = new DadosOrdemDeServico();
            this.ListarOs = dados.listarOrdemServicos(os);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (OrdemDeServico o : this.ListarOs) {

                if ("Aberta".equals(o.Status())) {
                    modelo.addElement(o.getNumero());
                }
            }

            jComboBoxConsultarOS.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    public OrdemGUIStatus() {
        initComponents();
        ListarNumeroOrdemDeServico();
        ResetarTabela();
        jLabelData.setVisible(false);
        jTextFieldData.setVisible(false);
        jLabelMotivoDescricao.setVisible(false);
        jTextFieldMotivoDescricao.setVisible(false);
        jButtonAlterarStatus.setVisible(false);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldData.setText(formato.format(new Date(System.currentTimeMillis())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelAviso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jButtonConsultarOs = new javax.swing.JButton();
        jLabelInformacao = new javax.swing.JLabel();
        jComboBoxConsultarOS = new javax.swing.JComboBox();
        jLabelData = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");

            jTextFieldData = new javax.swing.JFormattedTextField(data);
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jLabelMotivoDescricao = new javax.swing.JLabel();
        jTextFieldMotivoDescricao = new javax.swing.JTextField();
        jCheckBoxCancelar = new javax.swing.JCheckBox();
        jCheckBoxSolucionar = new javax.swing.JCheckBox();
        jButtonAlterarStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setText("Solucionar / Cancelar Ordem De Serviço");

        jLabelAviso.setText("Apenas ordems de serviço em aberto podem sofrer alterações");

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableConsultaMousePressed(evt);
            }
        });
        jTableConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableConsultaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);

        jButtonConsultarOs.setText("Consultar");
        jButtonConsultarOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarOsActionPerformed(evt);
            }
        });

        jLabelInformacao.setText("Selecione a Ordem de serviço desejada :");

        jComboBoxConsultarOS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelData.setText("Label:");

        jLabelMotivoDescricao.setText("LabelTexto:");

        jCheckBoxCancelar.setText("Cancelar");
        jCheckBoxCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCancelarActionPerformed(evt);
            }
        });

        jCheckBoxSolucionar.setText("Solucionar");
        jCheckBoxSolucionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSolucionarActionPerformed(evt);
            }
        });

        jButtonAlterarStatus.setText("Alterar Status");
        jButtonAlterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jComboBoxConsultarOS, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jButtonConsultarOs, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabelAviso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelInformacao))))
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxSolucionar)
                            .addComponent(jCheckBoxCancelar))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMotivoDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMotivoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelData)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jButtonAlterarStatus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultarOs)
                    .addComponent(jComboBoxConsultarOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInformacao))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSolucionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelData))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelMotivoDescricao))
                            .addComponent(jTextFieldMotivoDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButtonAlterarStatus)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarOsActionPerformed
        // TODO add your handling code here:

        try {

            if (jComboBoxConsultarOS.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem Ordem de serviço para consultar");
                dispose();
                return;
            }

            OrdemDeServico os = new OrdemDeServico();
            os.setNumero(Integer.parseInt(jComboBoxConsultarOS.getSelectedItem().toString()));

            DadosOrdemDeServico DadosOS = new DadosOrdemDeServico();

            this.ListarOs = DadosOS.listarOrdemServicos(os);

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Descrição Problema", "Status", "Numero", "Cliente_Cpf", "Matricula_funcionario", "Problema", "Data_Cadastro"});
            for (OrdemDeServico o : ListarOs) {

                if ("Aberta".equals(o.Status())) {
                    modelo.addRow(new Object[]{o.getDescricaoProblema(), o.getStatus(), o.getNumero(), o.getCliente().getCpf(), o.getFuncionario().getMatricula(), o.getClassificacaoProblema().getNome(), o.getDataCadastro()});

                }
            }

            jTableConsulta.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_jButtonConsultarOsActionPerformed

    private void jCheckBoxCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCancelarActionPerformed
        // TODO add your handling code here:

        if (jCheckBoxCancelar.isSelected()) {
            jCheckBoxSolucionar.setEnabled(false);

            jLabelData.setVisible(true);
            jLabelData.setText("Data do Cancelamento:");
            jTextFieldData.setVisible(true);
            jLabelMotivoDescricao.setVisible(true);
            jLabelMotivoDescricao.setText("Motivo Cancelamento:");
            jTextFieldMotivoDescricao.setVisible(true);
            jButtonAlterarStatus.setVisible(true);

        } else {
            jCheckBoxSolucionar.setEnabled(true);

            jLabelData.setVisible(false);
            jLabelData.setText("Data do Cancelamento:");
            jTextFieldData.setVisible(false);
            jLabelMotivoDescricao.setVisible(false);
            jLabelMotivoDescricao.setText("Motivo Cancelamento:");
            jTextFieldMotivoDescricao.setVisible(false);
            jButtonAlterarStatus.setVisible(false);

        }

    }//GEN-LAST:event_jCheckBoxCancelarActionPerformed

    private void jCheckBoxSolucionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSolucionarActionPerformed
        // TODO add your handling code here:

        if (jCheckBoxSolucionar.isSelected()) {
            jCheckBoxCancelar.setEnabled(false);

            jLabelData.setVisible(true);
            jLabelData.setText("Data da Solução:");
            jTextFieldData.setVisible(true);
            jLabelMotivoDescricao.setVisible(true);
            jLabelMotivoDescricao.setText("Descrição do Serviço:");
            jTextFieldMotivoDescricao.setVisible(true);
            jButtonAlterarStatus.setVisible(true);

        } else {
            jCheckBoxCancelar.setEnabled(true);
            jLabelData.setVisible(false);
            jLabelData.setText("Data da Solução:");
            jTextFieldData.setVisible(false);
            jLabelMotivoDescricao.setVisible(false);
            jLabelMotivoDescricao.setText("Descrição do Serviço:");
            jTextFieldMotivoDescricao.setVisible(false);
            jButtonAlterarStatus.setVisible(false);

        }
    }//GEN-LAST:event_jCheckBoxSolucionarActionPerformed

    private void jButtonAlterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarStatusActionPerformed
        // TODO add your handling code here:

        try {
            
            if (jComboBoxConsultarOS.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem Ordem de serviço para alterar");
                dispose();
                return;
            }
            
            if (jCheckBoxCancelar.isSelected() == true) {

                OrdemDeServico os = new OrdemDeServico();

                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date dataCancelamento = new java.sql.Date(formato.parse(jTextFieldData.getText()).getTime());

                os.setNumero(Integer.parseInt(jComboBoxConsultarOS.getSelectedItem().toString()));
                os.setDataCancelamento(dataCancelamento);
                os.setMotivoCancelamento(jTextFieldMotivoDescricao.getText());

                NegocioOrdemDeServico negocio = new NegocioOrdemDeServico();
                negocio.cancelarOrdemServico(os);

                JOptionPane.showMessageDialog(rootPane, "Ordem de serviço cancelada!");
                ListarNumeroOrdemDeServico();
                jTextFieldMotivoDescricao.setText("");

            }

            if (jCheckBoxSolucionar.isSelected() == true) {

                OrdemDeServico os = new OrdemDeServico();
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date dataSolucao = new java.sql.Date(formato.parse(jTextFieldData.getText()).getTime());
                os.setDataSolucao(dataSolucao);
                os.setDescricaoServico(jTextFieldMotivoDescricao.getText());
                os.setNumero(Integer.parseInt(jComboBoxConsultarOS.getSelectedItem().toString()));

                NegocioOrdemDeServico negocio = new NegocioOrdemDeServico();
                negocio.solucionarOrdemServico(os);

                JOptionPane.showMessageDialog(rootPane, "Ordem de serviço solucionada!");
                ListarNumeroOrdemDeServico();
                jTextFieldMotivoDescricao.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }


    }//GEN-LAST:event_jButtonAlterarStatusActionPerformed

    private void jTableConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableConsultaKeyTyped
        // TODO add your handling code here:
        jTableConsulta.editingCanceled(null);
        jTableConsulta.editingStopped(null);
    }//GEN-LAST:event_jTableConsultaKeyTyped

    private void jTableConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMousePressed
        // TODO add your handling code here:
        jTableConsulta.editingCanceled(null);
        jTableConsulta.editingStopped(null);
    }//GEN-LAST:event_jTableConsultaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemGUIStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarStatus;
    private javax.swing.JButton jButtonConsultarOs;
    private javax.swing.JCheckBox jCheckBoxCancelar;
    private javax.swing.JCheckBox jCheckBoxSolucionar;
    private javax.swing.JComboBox jComboBoxConsultarOS;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelInformacao;
    private javax.swing.JLabel jLabelMotivoDescricao;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldMotivoDescricao;
    // End of variables declaration//GEN-END:variables
}
