/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classe.ClassificacaoProblema;
import Classe.Cliente;
import Classe.Funcionario;
import Classe.OrdemDeServico;
import Dados.DadosClassificacaoProblema;
import Dados.DadosCliente;
import Dados.DadosFuncionario;
import Dados.DadosOrdemDeServico;
import Negocio.NegocioOrdemDeServico;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class OrdemGUIEditar extends javax.swing.JFrame {

    ArrayList<Cliente> respostaCpf = new ArrayList<>();
    ArrayList<Funcionario> respostaMatricula = new ArrayList<>();
    ArrayList<ClassificacaoProblema> respostaCodigo = new ArrayList<>();
    ArrayList<OrdemDeServico> ListarOs = new ArrayList<>();

    public void ResetarTabela() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Numero", "Cpf Cliente", "Matricula Funcionario", "Problema", "Data_Cadastro"});
        jTableConsulta.setModel(modelo);
    }

    public void listarCodigo() {

        try {

            ClassificacaoProblema classificacao = new ClassificacaoProblema();
            DadosClassificacaoProblema dados = new DadosClassificacaoProblema();

            this.respostaCodigo = dados.listarClassificacaoProblemas(classificacao);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (ClassificacaoProblema p : respostaCodigo) {
                modelo.addElement(p.getCodigo());
            }

            jComboBoxNovaClassificacao.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    public void listarMatricula() {

        try {

            Funcionario funcionario = new Funcionario();

            DadosFuncionario dados = new DadosFuncionario();

            this.respostaMatricula = dados.listarFuncionarios(funcionario);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (Funcionario f : respostaMatricula) {
                modelo.addElement(f.getMatricula());
            }

            jComboBoxNovoFuncionario.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e.getMessage());

        }

    }

    public void listarCpf() {

        try {

            Cliente cliente = new Cliente();

            DadosCliente dados = new DadosCliente();

            this.respostaCpf = dados.listarClientes(cliente);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (Cliente c : this.respostaCpf) {
                modelo.addElement(c.getCpf());
            }

            jComboBoxNovoCliente.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    public void ListarNumeroOrdemDeServico() {
        try {
            OrdemDeServico os = new OrdemDeServico();
            DadosOrdemDeServico dados = new DadosOrdemDeServico();
            this.ListarOs = dados.listarOrdemServicos(os);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (OrdemDeServico o : this.ListarOs) {

                if ("Aberta".equals(o.Status())) {
                    modelo.addElement(o.getNumero());
                }
            }

            jComboBoxConsultarOS.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    public OrdemGUIEditar() {
        initComponents();
        ListarNumeroOrdemDeServico();
        listarCpf();
        listarMatricula();
        listarCodigo();
        ResetarTabela();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonConsultarOrdem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxConsultarOS = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jComboBoxNovoFuncionario = new javax.swing.JComboBox();
        jComboBoxNovoCliente = new javax.swing.JComboBox();
        jComboBoxNovaClassificacao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonEditarOrdem = new javax.swing.JButton();
        jTextFieldNovaDescricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Selecione a ordem de serviço desejada:");

        jButtonConsultarOrdem.setText("Consultar");
        jButtonConsultarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarOrdemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Editar ordem de serviço");

        jComboBoxConsultarOS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableConsultaMousePressed(evt);
            }
        });
        jTableConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableConsultaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);

        jComboBoxNovoFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNovoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxNovaClassificacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Novo funcionário:");

        jLabel4.setText("Novo Cliente:");

        jLabel5.setText("Nova classificação do problema:");

        jButtonEditarOrdem.setText("Editar ");
        jButtonEditarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarOrdemActionPerformed(evt);
            }
        });

        jLabel6.setText("Nova descrição do problema:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56)
                                .addComponent(jComboBoxConsultarOS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsultarOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jTextFieldNovaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jComboBoxNovaClassificacao, 0, 169, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jComboBoxNovoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jButtonEditarOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxConsultarOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonConsultarOrdem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNovaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNovaClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarOrdem)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarOrdemActionPerformed
        try {

            if (jComboBoxConsultarOS.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem Ordem de serviço para editar");
                dispose();
                return;
            }

            OrdemDeServico os = new OrdemDeServico();
            os.setNumero(Integer.parseInt(jComboBoxConsultarOS.getSelectedItem().toString()));

            DadosOrdemDeServico DadosOS = new DadosOrdemDeServico();

            this.ListarOs = DadosOS.listarOrdemServicos(os);

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Status", "Numero", "Cliente_Cpf", "Matricula_funcionario", "Problema", "Data_Cadastro"});
            for (OrdemDeServico o : ListarOs) {

                if ("Aberta".equals(o.Status())) {
                    modelo.addRow(new Object[]{o.getStatus(), o.getNumero(), o.getCliente().getCpf(), o.getFuncionario().getMatricula(), o.getClassificacaoProblema().getNome(), o.getDataCadastro()});

                }
            }

            jTableConsulta.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_jButtonConsultarOrdemActionPerformed

    private void jButtonEditarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarOrdemActionPerformed
        try {

            if (jComboBoxConsultarOS.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem Ordem de serviço para editar");
                dispose();
                return;
            }

            OrdemDeServico os = new OrdemDeServico();

            os.setDescricaoProblema(jTextFieldNovaDescricao.getText());
            os.getCliente().setCpf(jComboBoxNovoCliente.getSelectedItem().toString());
            os.getClassificacaoProblema().setCodigo(Integer.parseInt(jComboBoxNovaClassificacao.getSelectedItem().toString()));
            os.getFuncionario().setMatricula(Integer.parseInt(jComboBoxNovoFuncionario.getSelectedItem().toString()));
            os.setNumero(Integer.parseInt(jComboBoxConsultarOS.getSelectedItem().toString()));

            NegocioOrdemDeServico negocio = new NegocioOrdemDeServico();
            negocio.editarOrdemServico(os);

            int resposta = JOptionPane.showConfirmDialog(rootPane, "Ordem de serviço editada com sucesso! \nDeseja Editar Outra Ordem de Serviço ?", "Sucesso", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if (resposta == JOptionPane.YES_OPTION) {

                ListarNumeroOrdemDeServico();
                ResetarTabela();

                jTextFieldNovaDescricao.setText("");

                jTextFieldNovaDescricao.requestFocus();

            } else {
                dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditarOrdemActionPerformed

    private void jTableConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableConsultaKeyTyped
        // TODO add your handling code here:
        jTableConsulta.editingCanceled(null);
        jTableConsulta.editingStopped(null);
    }//GEN-LAST:event_jTableConsultaKeyTyped

    private void jTableConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMousePressed
        // TODO add your handling code here:
        jTableConsulta.editingCanceled(null);
        jTableConsulta.editingStopped(null);
    }//GEN-LAST:event_jTableConsultaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemGUIEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemGUIEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarOrdem;
    private javax.swing.JButton jButtonEditarOrdem;
    private javax.swing.JComboBox jComboBoxConsultarOS;
    private javax.swing.JComboBox jComboBoxNovaClassificacao;
    private javax.swing.JComboBox jComboBoxNovoCliente;
    private javax.swing.JComboBox jComboBoxNovoFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldNovaDescricao;
    // End of variables declaration//GEN-END:variables
}
