/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classe.ClassificacaoProblema;
import Dados.DadosClassificacaoProblema;
import Negocio.NegocioClassificacaoProblema;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class ProblemaGUIRemover extends javax.swing.JFrame {

    ArrayList<ClassificacaoProblema> respostaCodigo;

    public void ResetarDados() {
        jTextAreaDescricao.setText("");
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[] {"Nome"});
        jTableNome.setModel(modelo);
    }

    public void ListarCodigo() {

        try {
            ClassificacaoProblema problema = new ClassificacaoProblema();
            DadosClassificacaoProblema dados = new DadosClassificacaoProblema();

            this.respostaCodigo = dados.listarClassificacaoProblemas(problema);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            for (ClassificacaoProblema c : this.respostaCodigo) {
                modelo.addElement(c.getCodigo());
            }

            jComboBoxCodigoClassificacaoProblemaRemover.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public ProblemaGUIRemover() {
        initComponents();
        ListarCodigo();
        jTextAreaDescricao.setWrapStyleWord(true);
        jTextAreaDescricao.setLineWrap(true);
        ResetarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonConsultarClassificacaoProblemaRemover2 = new javax.swing.JButton();
        jButtonRemoverClassificacaoProblema = new javax.swing.JButton();
        jLabelEscolhaClassificacaoProblemaRemover = new javax.swing.JLabel();
        jComboBoxCodigoClassificacaoProblemaRemover = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNome = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTitulo.setText("Remover Problema");

        jButtonConsultarClassificacaoProblemaRemover2.setText("Consultar");
        jButtonConsultarClassificacaoProblemaRemover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarClassificacaoProblemaRemover2ActionPerformed(evt);
            }
        });

        jButtonRemoverClassificacaoProblema.setText("Remover");
        jButtonRemoverClassificacaoProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverClassificacaoProblemaActionPerformed(evt);
            }
        });

        jLabelEscolhaClassificacaoProblemaRemover.setText("Selecione o Código da Classificação Problema");

        jComboBoxCodigoClassificacaoProblemaRemover.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextAreaDescricao.setEditable(false);
        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDescricao);

        jTableNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableNome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(jButtonRemoverClassificacaoProblema))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelEscolhaClassificacaoProblemaRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCodigoClassificacaoProblemaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonConsultarClassificacaoProblemaRemover2)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelTitulo)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEscolhaClassificacaoProblemaRemover)
                    .addComponent(jComboBoxCodigoClassificacaoProblemaRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarClassificacaoProblemaRemover2))
                .addGap(183, 183, 183)
                .addComponent(jButtonRemoverClassificacaoProblema)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(200, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarClassificacaoProblemaRemover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarClassificacaoProblemaRemover2ActionPerformed
        // TODO add your handling code here:
        // Botão Consultar
        try {

            if (jComboBoxCodigoClassificacaoProblemaRemover.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sem Problema para resolver");
                return;
            }

            ClassificacaoProblema classificacaoProblema = new ClassificacaoProblema();
            classificacaoProblema.setCodigo(Integer.parseInt(jComboBoxCodigoClassificacaoProblemaRemover.getSelectedItem().toString()));

            DadosClassificacaoProblema dadosClassificacaoProblema = new DadosClassificacaoProblema();

            respostaCodigo = dadosClassificacaoProblema.listarClassificacaoProblemas(classificacaoProblema);

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Nome"});

            for (ClassificacaoProblema c : respostaCodigo) {
                
                modelo.addRow(new Object[]{c.getNome()});
                jTextAreaDescricao.setText(c.getDescricao());

            }

            jTableNome.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarClassificacaoProblemaRemover2ActionPerformed

    private void jButtonRemoverClassificacaoProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverClassificacaoProblemaActionPerformed
        // TODO add your handling code here:
        // Botão Remover
        try {

            ClassificacaoProblema classificacaoProblema = new ClassificacaoProblema();
            classificacaoProblema.setCodigo(Integer.parseInt(jComboBoxCodigoClassificacaoProblemaRemover.getSelectedItem().toString()));
            NegocioClassificacaoProblema negocio = new NegocioClassificacaoProblema();
            negocio.removerClassificacaoProblema(classificacaoProblema);

            int resposta = JOptionPane.showConfirmDialog(rootPane, "Classificação Problema removida! \nDeseja remover outro Problema ?", "Sucesso", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

            if (resposta == JOptionPane.YES_OPTION) {
                ListarCodigo();
                ResetarDados();

                jComboBoxCodigoClassificacaoProblemaRemover.requestFocus();
            } else {
                dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }


    }//GEN-LAST:event_jButtonRemoverClassificacaoProblemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProblemaGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProblemaGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProblemaGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProblemaGUIRemover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProblemaGUIRemover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarClassificacaoProblemaRemover2;
    private javax.swing.JButton jButtonRemoverClassificacaoProblema;
    private javax.swing.JComboBox<String> jComboBoxCodigoClassificacaoProblemaRemover;
    private javax.swing.JLabel jLabelEscolhaClassificacaoProblemaRemover;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableNome;
    private javax.swing.JTextArea jTextAreaDescricao;
    // End of variables declaration//GEN-END:variables
}
