/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classe.OrdemDeServico;
import Dados.DadosOrdemDeServico;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class TelaInicial extends javax.swing.JFrame {

    public void listarOrdemDeServicos(){
        
        try{
            OrdemDeServico ordemServico = new OrdemDeServico();
            ArrayList<OrdemDeServico> resposta;
        
            DadosOrdemDeServico dados = new DadosOrdemDeServico();
            resposta = dados.listarOrdemServicos(ordemServico);
        
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object []{"Número", "Cpf Cliente" , "Matricula Funcionario" ,"Status", "Data de Cadastro"});
            
            for (OrdemDeServico os : resposta) {
                modelo.addRow(new Object[]{os.getNumero() , os.getCliente().getCpf() , os.getFuncionario().getMatricula(), os.Status() , os.getDataCadastro()});
            }
        
            
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
 
        
    }
    public TelaInicial() {
        initComponents();
        listarOrdemDeServicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundo3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItemRemoverCliente = new javax.swing.JMenuItem();
        jMenuItemVizualizarCliente = new javax.swing.JMenuItem();
        jMenuItemEditarCliente = new javax.swing.JMenuItem();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuItemCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuItemRemoverFuncionario = new javax.swing.JMenuItem();
        jMenuItemVizualizarFuncionario = new javax.swing.JMenuItem();
        jMenuItemEditarFuncionario = new javax.swing.JMenuItem();
        jMenuProblema = new javax.swing.JMenu();
        jMenuItemCadastrarProblema = new javax.swing.JMenuItem();
        jMenuItemRemoverProblema = new javax.swing.JMenuItem();
        jMenuItemVizualizarProblema = new javax.swing.JMenuItem();
        jMenuItemEditarProblema = new javax.swing.JMenuItem();
        jMenuOrdemServico = new javax.swing.JMenu();
        jMenuItemCadastrarOs = new javax.swing.JMenuItem();
        jMenuItemRemoverOs = new javax.swing.JMenuItem();
        jMenuItemVizualizarOs = new javax.swing.JMenuItem();
        jMenuItemEditarOs = new javax.swing.JMenuItem();
        jMenuItemStatus = new javax.swing.JMenuItem();

        jLabelFundo3.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCliente.setText("Clientes");

        jMenuItemCadastrarCliente.setText("Cadastrar Cliente");
        jMenuItemCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemCadastrarCliente);

        jMenuItemRemoverCliente.setText("Remover Cliente");
        jMenuItemRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemRemoverCliente);

        jMenuItemVizualizarCliente.setText("Vizualizar Clientes");
        jMenuItemVizualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVizualizarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemVizualizarCliente);

        jMenuItemEditarCliente.setText("Editar Cliente");
        jMenuItemEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemEditarCliente);

        jMenuBar1.add(jMenuCliente);

        jMenuFuncionario.setText("Funcionarios");

        jMenuItemCadastrarFuncionario.setText("Cadastrar Funcionario");
        jMenuItemCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemCadastrarFuncionario);

        jMenuItemRemoverFuncionario.setText("Remover Funcionario");
        jMenuItemRemoverFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemRemoverFuncionario);

        jMenuItemVizualizarFuncionario.setText("Vizualizar Funcionarios");
        jMenuItemVizualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVizualizarFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemVizualizarFuncionario);

        jMenuItemEditarFuncionario.setText("Editar Funcionario");
        jMenuItemEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarFuncionarioActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuItemEditarFuncionario);

        jMenuBar1.add(jMenuFuncionario);

        jMenuProblema.setText("Classificação do Problema");

        jMenuItemCadastrarProblema.setText("Cadastrar Problema");
        jMenuItemCadastrarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarProblemaActionPerformed(evt);
            }
        });
        jMenuProblema.add(jMenuItemCadastrarProblema);

        jMenuItemRemoverProblema.setText("Remover Problema");
        jMenuItemRemoverProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverProblemaActionPerformed(evt);
            }
        });
        jMenuProblema.add(jMenuItemRemoverProblema);

        jMenuItemVizualizarProblema.setText("Vizualizar Problemas");
        jMenuItemVizualizarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVizualizarProblemaActionPerformed(evt);
            }
        });
        jMenuProblema.add(jMenuItemVizualizarProblema);

        jMenuItemEditarProblema.setText("Editar Problema");
        jMenuItemEditarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarProblemaActionPerformed(evt);
            }
        });
        jMenuProblema.add(jMenuItemEditarProblema);

        jMenuBar1.add(jMenuProblema);

        jMenuOrdemServico.setText("Ordem de Serviço");

        jMenuItemCadastrarOs.setText("Cadastrar Os");
        jMenuItemCadastrarOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarOsActionPerformed(evt);
            }
        });
        jMenuOrdemServico.add(jMenuItemCadastrarOs);

        jMenuItemRemoverOs.setText("Remover Os");
        jMenuItemRemoverOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverOsActionPerformed(evt);
            }
        });
        jMenuOrdemServico.add(jMenuItemRemoverOs);

        jMenuItemVizualizarOs.setText("Vizualizar Os");
        jMenuItemVizualizarOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVizualizarOsActionPerformed(evt);
            }
        });
        jMenuOrdemServico.add(jMenuItemVizualizarOs);

        jMenuItemEditarOs.setText("Editar Os");
        jMenuItemEditarOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarOsActionPerformed(evt);
            }
        });
        jMenuOrdemServico.add(jMenuItemEditarOs);

        jMenuItemStatus.setText("Alterar Status Os");
        jMenuItemStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStatusActionPerformed(evt);
            }
        });
        jMenuOrdemServico.add(jMenuItemStatus);

        jMenuBar1.add(jMenuOrdemServico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1114, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClienteActionPerformed
        // TODO add your handling code here:
        ClienteGUICadastro tela = new ClienteGUICadastro();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarClienteActionPerformed

    private void jMenuItemRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverClienteActionPerformed
        // TODO add your handling code here:
        ClienteGUIRemover tela = new ClienteGUIRemover();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRemoverClienteActionPerformed

    private void jMenuItemVizualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVizualizarClienteActionPerformed
        // TODO add your handling code here:
        ClienteGUIVizualizar tela = new ClienteGUIVizualizar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemVizualizarClienteActionPerformed

    private void jMenuItemEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarClienteActionPerformed
        // TODO add your handling code here:
        ClienteGUIEditar tela = new ClienteGUIEditar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarClienteActionPerformed

    private void jMenuItemCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        FuncionarioGUICadastrar tela = new FuncionarioGUICadastrar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarFuncionarioActionPerformed

    private void jMenuItemVizualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVizualizarFuncionarioActionPerformed
        // TODO add your handling code here:
        FuncionarioGUIVizualizar tela = new FuncionarioGUIVizualizar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemVizualizarFuncionarioActionPerformed

    private void jMenuItemRemoverFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverFuncionarioActionPerformed
        // TODO add your handling code here:
        FuncionarioGUIRemover tela = new FuncionarioGUIRemover();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRemoverFuncionarioActionPerformed

    private void jMenuItemEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarFuncionarioActionPerformed
        // TODO add your handling code here:
        FuncionarioGUIEditar tela = new FuncionarioGUIEditar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarFuncionarioActionPerformed

    private void jMenuItemCadastrarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarProblemaActionPerformed
        // TODO add your handling code here:
        ProblemaGUICadastrar tela = new ProblemaGUICadastrar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarProblemaActionPerformed

    private void jMenuItemRemoverProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverProblemaActionPerformed
        // TODO add your handling code here:
        ProblemaGUIRemover tela = new ProblemaGUIRemover();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRemoverProblemaActionPerformed

    private void jMenuItemVizualizarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVizualizarProblemaActionPerformed
        // TODO add your handling code here:
        ProblemaGUIVizualizar tela = new ProblemaGUIVizualizar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemVizualizarProblemaActionPerformed

    private void jMenuItemEditarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarProblemaActionPerformed
        // TODO add your handling code here:
        ProblemaGUIEditar tela = new ProblemaGUIEditar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarProblemaActionPerformed

    private void jMenuItemCadastrarOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarOsActionPerformed
        // TODO add your handling code here:
        OrdemGUICadastrar tela = new OrdemGUICadastrar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarOsActionPerformed

    private void jMenuItemRemoverOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverOsActionPerformed
        // TODO add your handling code here:
        OrdemGUIRemover tela = new OrdemGUIRemover();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRemoverOsActionPerformed

    private void jMenuItemVizualizarOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVizualizarOsActionPerformed
        // TODO add your handling code here:,
        OrdemGUIVizualizar tela = new OrdemGUIVizualizar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemVizualizarOsActionPerformed

    private void jMenuItemEditarOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarOsActionPerformed
        // TODO add your handling code here:
        OrdemGUIEditar tela = new OrdemGUIEditar();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarOsActionPerformed

    private void jMenuItemStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStatusActionPerformed
        // TODO add your handling code here:
        OrdemGUIStatus tela = new OrdemGUIStatus();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundo3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarFuncionario;
    private javax.swing.JMenuItem jMenuItemCadastrarOs;
    private javax.swing.JMenuItem jMenuItemCadastrarProblema;
    private javax.swing.JMenuItem jMenuItemEditarCliente;
    private javax.swing.JMenuItem jMenuItemEditarFuncionario;
    private javax.swing.JMenuItem jMenuItemEditarOs;
    private javax.swing.JMenuItem jMenuItemEditarProblema;
    private javax.swing.JMenuItem jMenuItemRemoverCliente;
    private javax.swing.JMenuItem jMenuItemRemoverFuncionario;
    private javax.swing.JMenuItem jMenuItemRemoverOs;
    private javax.swing.JMenuItem jMenuItemRemoverProblema;
    private javax.swing.JMenuItem jMenuItemStatus;
    private javax.swing.JMenuItem jMenuItemVizualizarCliente;
    private javax.swing.JMenuItem jMenuItemVizualizarFuncionario;
    private javax.swing.JMenuItem jMenuItemVizualizarOs;
    private javax.swing.JMenuItem jMenuItemVizualizarProblema;
    private javax.swing.JMenu jMenuOrdemServico;
    private javax.swing.JMenu jMenuProblema;
    // End of variables declaration//GEN-END:variables
}
